package corn;
import java.util.LinkedList;
import javax.swing.table.*;
import javax.swing.event.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bor1bro
 */
public class NewJFrame extends javax.swing.JFrame /*implements TableModelListener*/{

    private LinkedList<RecIntegral> rows = new LinkedList<>();
    private int offset = 0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        //jTable1.getModel().addTableModelListener(this);
    }
//    @Override
//    public void tableChanged(TableModelEvent event)
//    {
//        if (event.getPoint)
//        {
//            TableModel model = (TableModel)event.getSource();
//            int eventRowIndex = event.getFirstRow();
//            RecIntegral eventRow = rows.get(eventRowIndex);
//            int eventColumn = event.getColumn();
//        
//            double newData = ((Number)model.getValueAt(eventRowIndex, eventColumn)).doubleValue();
//        
//            switch(eventColumn)
//            {
//                case 0:
//                {
//                    eventRow.setMinValue(newData);
//                }
//                case 1:
//                {
//                    eventRow.setMaxValue(newData);
//                }
//                case 2:
//                {
//                    eventRow.setStepValue(newData);
//                }
//                default:
//                {
//                    //hz
//                }
//            }
//        
//            rows.set(eventRowIndex, eventRow);
//        }
        
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stepValueLabel = new javax.swing.JLabel();
        maxValueLabel = new javax.swing.JLabel();
        minValueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        integralTable = new javax.swing.JTable();
        resultButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        minValueTextField = new javax.swing.JTextField();
        maxValueTextField = new javax.swing.JTextField();
        stepValueTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        fillButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("sin(x)");
        setBackground(new java.awt.Color(136, 207, 187));
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setName("sin(x)"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(136, 207, 187));

        stepValueLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        stepValueLabel.setForeground(new java.awt.Color(44, 78, 68));
        stepValueLabel.setText("STEP");

        maxValueLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        maxValueLabel.setForeground(new java.awt.Color(44, 78, 68));
        maxValueLabel.setText("MAX");

        minValueLabel.setBackground(new java.awt.Color(136, 207, 187));
        minValueLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        minValueLabel.setForeground(new java.awt.Color(44, 78, 68));
        minValueLabel.setText("MIN");
        minValueLabel.setOpaque(true);

        jScrollPane1.setBackground(new java.awt.Color(228, 255, 241));
        jScrollPane1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        integralTable.setBackground(new java.awt.Color(228, 255, 241));
        integralTable.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        integralTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MIN", "MAX", "STEP", "RESULT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        integralTable.setToolTipText("ne nado bilo eto kushat'");
        integralTable.setGridColor(new java.awt.Color(68, 121, 105));
        integralTable.setName(""); // NOI18N
        integralTable.setSelectionBackground(new java.awt.Color(146, 143, 131));
        integralTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(integralTable);
        if (integralTable.getColumnModel().getColumnCount() > 0) {
            integralTable.getColumnModel().getColumn(0).setResizable(false);
            integralTable.getColumnModel().getColumn(1).setResizable(false);
            integralTable.getColumnModel().getColumn(2).setResizable(false);
            integralTable.getColumnModel().getColumn(3).setResizable(false);
        }

        resultButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        resultButton.setText("RESULT");
        resultButton.setBorder(null);
        resultButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstimateResult(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        removeButton.setText("REMOVE");
        removeButton.setBorder(null);
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveRow(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        addButton.setText("ADD");
        addButton.setBorder(null);
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddRow(evt);
            }
        });

        minValueTextField.setBackground(new java.awt.Color(228, 255, 241));
        minValueTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        maxValueTextField.setBackground(new java.awt.Color(228, 255, 241));
        maxValueTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        stepValueTextField.setBackground(new java.awt.Color(228, 255, 241));
        stepValueTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(228, 255, 241));

        titleLabel.setBackground(new java.awt.Color(155, 209, 185));
        titleLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(44, 78, 68));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("JEP-4 DEFINITIVE EDITION");
        titleLabel.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel)
        );

        clearButton.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearTable(evt);
            }
        });

        fillButton.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        fillButton.setText("FILL");
        fillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FillTable(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(minValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minValueTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxValueTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stepValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stepValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fillButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(minValueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(maxValueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stepValueLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stepValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fillButton)
                .addGap(13, 13, 13)
                .addComponent(clearButton)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void AddRow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddRow
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) integralTable.getModel();
        if (!minValueTextField.getText().isEmpty() && !maxValueTextField.getText().isEmpty() && !stepValueTextField.getText().isEmpty())
        {
            RecIntegral row = new RecIntegral(Double.parseDouble(minValueTextField.getText()),
                                              Double.parseDouble(maxValueTextField.getText()),
                                              Double.parseDouble(stepValueTextField.getText()),
                                              0.0);
            if (row.getMinValue() != 0 && row.getMaxValue() != 0 && row.getStepValue() != 0)
            {
                rows.add(row);
                Object[] rowData = 
                {   
                    rows.getLast().getMinValue(),
                    rows.getLast().getMaxValue(),
                    rows.getLast().getStepValue(),
                    null
                };
                model.addRow(rowData);
            }
        }
        integralTable.setModel(model);
    }//GEN-LAST:event_AddRow

    private void RemoveRow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveRow
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) integralTable.getModel();
        if (integralTable.getSelectedColumnCount() != 0 && integralTable.getRowCount() != 0)
        {
            int rowNum = integralTable.getSelectedRows().length;
            for (int index = 0; index < rowNum; index++)
            {
                rows.remove(integralTable.getSelectedRow() + offset);
                model.removeRow(integralTable.getSelectedRow());
            } 
            
        }       
        integralTable.setModel(model);
    }//GEN-LAST:event_RemoveRow

    private void EstimateResult(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstimateResult
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) integralTable.getModel();
        for (int index = 0; index < model.getRowCount(); index++)
        {
            double resultValue = 0.0;
            double minValue = ((Number) model.getValueAt(index, 0)).doubleValue();
            double maxValue = ((Number) model.getValueAt(index, 1)).doubleValue();
            double stepValue = ((Number) model.getValueAt(index, 2)).doubleValue();
            
            Integral integral = new Integral(minValue, maxValue, stepValue);
        
            if((maxValue > minValue) & stepValue < (maxValue - minValue))
            {
                resultValue = integral.Estimate();
                if (model.getRowCount() == rows.size())
                {
                    rows.set(index, new RecIntegral(minValue, maxValue, stepValue, resultValue));
                }
                else
                {
                    rows.set(index + offset, new RecIntegral(minValue, maxValue, stepValue, resultValue));
                }
                model.setValueAt(resultValue, index, 3);
            }
        }
    }//GEN-LAST:event_EstimateResult

    private void FillTable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FillTable
        //fill
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) integralTable.getModel();
        offset = 0;
        if (model.getRowCount() == 0)
        {
            for (int index = 0; index < rows.size(); index++)
            {
                RecIntegral row = rows.get(index);
                Object[] rowData =
                {
                    row.getMinValue(),
                    row.getMaxValue(),
                    row.getStepValue(),
                    row.getResultValue()
                };
                model.addRow(rowData);
            }
        }
        
    }//GEN-LAST:event_FillTable

    private void ClearTable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearTable
        //clear
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) integralTable.getModel();
        offset = model.getRowCount();
        for (int index = model.getRowCount() - 1; index >= 0; index--)
        {
            model.removeRow(index);
        }
        integralTable.setModel(model);
    }//GEN-LAST:event_ClearTable

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton fillButton;
    private javax.swing.JTable integralTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maxValueLabel;
    private javax.swing.JTextField maxValueTextField;
    private javax.swing.JLabel minValueLabel;
    private javax.swing.JTextField minValueTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton resultButton;
    private javax.swing.JLabel stepValueLabel;
    private javax.swing.JTextField stepValueTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
