package corn;
import javax.swing.*;
import javax.swing.filechooser.FileSystemView;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.util.LinkedList;
import java.io.Serializable;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Scanner;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.FileInputStream;
import java.util.HashSet;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bor1bro
 */
public class NewJFrame extends javax.swing.JFrame implements Serializable{

    private LinkedList<RecIntegral> rows = new LinkedList<>();
    private int offset = 0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void ClearModel()
    {
        //clear
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) integralTable.getModel();
        offset = model.getRowCount();
        for (int index = model.getRowCount() - 1; index >= 0; index--)
        {
            model.removeRow(index);
        }
        integralTable.setModel(model);
    }
    
    private void FillModel()
    {
        //fill
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) integralTable.getModel();
        offset = 0;
        if (model.getRowCount() == 0)
        {
            for (int index = 0; index < rows.size(); index++)
            {
                RecIntegral row = rows.get(index);
                Object[] rowData =
                {
                    row.getMinValue(),
                    row.getMaxValue(),
                    row.getStepValue(),
                    row.getResultValue()
                };
                model.addRow(rowData);
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        stepValueLabel = new javax.swing.JLabel();
        maxValueLabel = new javax.swing.JLabel();
        minValueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        integralTable = new javax.swing.JTable();
        resultButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        minValueTextField = new javax.swing.JTextField();
        maxValueTextField = new javax.swing.JTextField();
        stepValueTextField = new javax.swing.JTextField();
        nameLabelPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        fillButton = new javax.swing.JButton();
        unserializedSaveButton = new javax.swing.JButton();
        unserializedLoadButton = new javax.swing.JButton();
        serializedSaveButton = new javax.swing.JButton();
        serializedLoadButton = new javax.swing.JButton();
        middleLinePanel = new javax.swing.JPanel();
        lowerLinePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("sin(x)");
        setBackground(new java.awt.Color(136, 207, 187));
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setName("sin(x)"); // NOI18N
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(136, 207, 187));

        stepValueLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        stepValueLabel.setForeground(new java.awt.Color(44, 78, 68));
        stepValueLabel.setText("STEP");

        maxValueLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        maxValueLabel.setForeground(new java.awt.Color(44, 78, 68));
        maxValueLabel.setText("MAX");

        minValueLabel.setBackground(new java.awt.Color(136, 207, 187));
        minValueLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        minValueLabel.setForeground(new java.awt.Color(44, 78, 68));
        minValueLabel.setText("MIN");
        minValueLabel.setOpaque(true);

        jScrollPane1.setBackground(new java.awt.Color(228, 255, 241));
        jScrollPane1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        integralTable.setBackground(new java.awt.Color(228, 255, 241));
        integralTable.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        integralTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MIN", "MAX", "STEP", "RESULT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        integralTable.setToolTipText("ne nado bilo eto kushat'");
        integralTable.setGridColor(new java.awt.Color(68, 121, 105));
        integralTable.setName(""); // NOI18N
        integralTable.setSelectionBackground(new java.awt.Color(146, 143, 131));
        integralTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(integralTable);
        if (integralTable.getColumnModel().getColumnCount() > 0) {
            integralTable.getColumnModel().getColumn(0).setResizable(false);
            integralTable.getColumnModel().getColumn(1).setResizable(false);
            integralTable.getColumnModel().getColumn(2).setResizable(false);
            integralTable.getColumnModel().getColumn(3).setResizable(false);
        }

        resultButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        resultButton.setText("RESULT");
        resultButton.setBorder(null);
        resultButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstimateResult(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        removeButton.setText("REMOVE");
        removeButton.setBorder(null);
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveRow(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        addButton.setText("ADD");
        addButton.setBorder(null);
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddRow(evt);
            }
        });

        minValueTextField.setBackground(new java.awt.Color(228, 255, 241));
        minValueTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        maxValueTextField.setBackground(new java.awt.Color(228, 255, 241));
        maxValueTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        stepValueTextField.setBackground(new java.awt.Color(228, 255, 241));
        stepValueTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        nameLabelPanel.setBackground(new java.awt.Color(228, 255, 241));

        titleLabel.setBackground(new java.awt.Color(155, 209, 185));
        titleLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(44, 78, 68));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("JEP-4 DEFINITIVE EDITION");
        titleLabel.setFocusable(false);

        javax.swing.GroupLayout nameLabelPanelLayout = new javax.swing.GroupLayout(nameLabelPanel);
        nameLabelPanel.setLayout(nameLabelPanelLayout);
        nameLabelPanelLayout.setHorizontalGroup(
            nameLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        nameLabelPanelLayout.setVerticalGroup(
            nameLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel)
        );

        clearButton.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearTable(evt);
            }
        });

        fillButton.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        fillButton.setText("FILL");
        fillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FillTable(evt);
            }
        });

        unserializedSaveButton.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        unserializedSaveButton.setText("SAVE");
        unserializedSaveButton.setPreferredSize(new java.awt.Dimension(73, 25));
        unserializedSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unserializedSaveButtonMouseClicked(evt);
            }
        });

        unserializedLoadButton.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        unserializedLoadButton.setText("LOAD");
        unserializedLoadButton.setPreferredSize(new java.awt.Dimension(73, 25));
        unserializedLoadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unserializedLoadButtonMouseClicked(evt);
            }
        });

        serializedSaveButton.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        serializedSaveButton.setText("SAVE binary");
        serializedSaveButton.setPreferredSize(new java.awt.Dimension(73, 25));
        serializedSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serializedSaveButtonMouseClicked(evt);
            }
        });

        serializedLoadButton.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        serializedLoadButton.setText("LOAD binary");
        serializedLoadButton.setPreferredSize(new java.awt.Dimension(73, 25));
        serializedLoadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serializedLoadButtonMouseClicked(evt);
            }
        });

        middleLinePanel.setBackground(new java.awt.Color(228, 255, 241));
        middleLinePanel.setPreferredSize(new java.awt.Dimension(392, 8));

        javax.swing.GroupLayout middleLinePanelLayout = new javax.swing.GroupLayout(middleLinePanel);
        middleLinePanel.setLayout(middleLinePanelLayout);
        middleLinePanelLayout.setHorizontalGroup(
            middleLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        middleLinePanelLayout.setVerticalGroup(
            middleLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        lowerLinePanel.setBackground(new java.awt.Color(228, 255, 241));
        lowerLinePanel.setPreferredSize(new java.awt.Dimension(392, 8));

        javax.swing.GroupLayout lowerLinePanelLayout = new javax.swing.GroupLayout(lowerLinePanel);
        lowerLinePanel.setLayout(lowerLinePanelLayout);
        lowerLinePanelLayout.setHorizontalGroup(
            lowerLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        lowerLinePanelLayout.setVerticalGroup(
            lowerLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(middleLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
            .addComponent(lowerLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(minValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minValueTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxValueTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(stepValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(unserializedLoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serializedLoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stepValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fillButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(unserializedSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serializedSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(minValueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(maxValueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stepValueLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stepValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(middleLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(fillButton)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lowerLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unserializedSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serializedSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serializedLoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unserializedLoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
        );

        unserializedSaveButton.getAccessibleContext().setAccessibleName("unserializedSaveButton");
        unserializedLoadButton.getAccessibleContext().setAccessibleName("unserializedLoadButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void AddRow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddRow
        // add 
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) integralTable.getModel();
        if (!minValueTextField.getText().isEmpty() && !maxValueTextField.getText().isEmpty() && !stepValueTextField.getText().isEmpty())
        {
            RecIntegral row = new RecIntegral(Double.parseDouble(minValueTextField.getText()),
                                              Double.parseDouble(maxValueTextField.getText()),
                                              Double.parseDouble(stepValueTextField.getText()),
                                              0.0);
            if (row.getMinValue() != 0 && row.getMaxValue() != 0 && row.getStepValue() != 0)
            {
                rows.add(row);
                Object[] rowData = 
                {   
                    rows.getLast().getMinValue(),
                    rows.getLast().getMaxValue(),
                    rows.getLast().getStepValue(),
                    null
                };
                model.addRow(rowData);
            }
        }
        integralTable.setModel(model);
    }//GEN-LAST:event_AddRow

    private void RemoveRow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveRow
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) integralTable.getModel();
        if (integralTable.getSelectedColumnCount() != 0 && integralTable.getRowCount() != 0)
        {
            int rowNum = integralTable.getSelectedRows().length;
            for (int index = 0; index < rowNum; index++)
            {
                rows.remove(integralTable.getSelectedRow() + offset);
                model.removeRow(integralTable.getSelectedRow());
            } 
            
        }       
        integralTable.setModel(model);
    }//GEN-LAST:event_RemoveRow

    private void EstimateResult(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstimateResult
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) integralTable.getModel();
        System.out.println("-");
        
        for (int index = 0; index < model.getRowCount(); index++)
        {
            int setIndex = index;
            
            double resultValue = 0.0;
            double minValue = ((Number) model.getValueAt(index, 0)).doubleValue();
            double maxValue = ((Number) model.getValueAt(index, 1)).doubleValue();
            double stepValue = ((Number) model.getValueAt(index, 2)).doubleValue();
            
            RecIntegral integral = new RecIntegral(minValue, maxValue, stepValue, resultValue);
            
            if ((integral.getMaxValue() > integral.getMinValue()))
            {
                Thread estimation = new Thread(() -> 
                    {
                        double resultEstimated = integral.Estimate();
                        if (model.getRowCount() == rows.size())
                        {
                            rows.set(setIndex, new RecIntegral(integral.getMinValue(), integral.getMaxValue(), integral.getStepValue(), resultEstimated));
                        }
                        else
                        {
                            rows.set(setIndex + offset, new RecIntegral(integral.getMinValue(), integral.getMaxValue(), integral.getStepValue(), resultEstimated));
                        }
                        model.setValueAt(resultEstimated, setIndex, 3);              
                    }
                );
                estimation.start();
            }
        }
    }//GEN-LAST:event_EstimateResult

    private void FillTable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FillTable
        FillModel();
    }//GEN-LAST:event_FillTable
  
    private void ClearTable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearTable
        ClearModel();
    }//GEN-LAST:event_ClearTable
    
    private void unserializedSaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unserializedSaveButtonMouseClicked
        // save
        try
        {
            String path = null;
            JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            fileChooser.setAcceptAllFileFilterUsed(false);
            FileNameExtensionFilter filter = new FileNameExtensionFilter("UNSERIALIZED FILES", "txt");
            fileChooser.addChoosableFileFilter(filter);
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.setCurrentDirectory(new File("F://джава/corn"));
            int returnValue = fileChooser.showSaveDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION)
            {
                File selectedFile = fileChooser.getSelectedFile();
                path = selectedFile.getAbsolutePath();
            }
            
            FileWriter databaseFile = new FileWriter(path);          
            for (int index = 0; index < rows.size(); index++)
            {
                String rowToWrite = "";
                rowToWrite = rowToWrite.concat(String.valueOf(rows.get(index).getMinValue()) + ", ")
                                       .concat(String.valueOf(rows.get(index).getMaxValue()) + ", ")
                                       .concat(String.valueOf(rows.get(index).getStepValue()) + ", ")
                                       .concat(String.valueOf(rows.get(index).getResultValue()));
                databaseFile.write(rowToWrite + "\n");  
            }
            databaseFile.close();
        }
        catch(IOException exception)
        {
            System.out.println(exception);
        }
        
    }//GEN-LAST:event_unserializedSaveButtonMouseClicked

    private void unserializedLoadButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unserializedLoadButtonMouseClicked
        // load
        try
        {
            String path = null;
            JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            fileChooser.setAcceptAllFileFilterUsed(false);
            FileNameExtensionFilter filter = new FileNameExtensionFilter("UNSERIALIZED FILES", "txt");
            fileChooser.addChoosableFileFilter(filter);
            fileChooser.setCurrentDirectory(new File("F://джава/corn"));
            int returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION)
            {
                File selectedFile = fileChooser.getSelectedFile();
                path = selectedFile.getAbsolutePath();
            }
            
            FileReader databaseFile = new FileReader(path);
            Scanner databaseScanner = new Scanner(databaseFile);
            
            rows.clear();
            ClearModel();
            
            while(databaseScanner.hasNextLine())
            {
                String rowString = databaseScanner.nextLine();
                String[] valueStrings = rowString.split(", ");
                double[] values = new double[valueStrings.length];
                for (int index = 0; index < valueStrings.length; index++)
                {
                   values[index] = Double.parseDouble(valueStrings[index]);
                }
                rows.add(new RecIntegral(values[0], values[1], values[2], values[3]));
            }
            
            FillModel();
            databaseFile.close();
        }
        catch(IOException exception)
        {
            System.out.println(exception);
        }
    }//GEN-LAST:event_unserializedLoadButtonMouseClicked

    private void serializedSaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serializedSaveButtonMouseClicked
        try
        {
            File outputFile = null;
            JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            fileChooser.setAcceptAllFileFilterUsed(false);
            FileNameExtensionFilter filter = new FileNameExtensionFilter("SERIALIZED FILES", "ser");
            fileChooser.addChoosableFileFilter(filter);
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.setCurrentDirectory(new File("F://джава/corn"));
            int returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION)
            {
                File selectedFile = fileChooser.getSelectedFile();
                outputFile = new File(selectedFile.getAbsolutePath());
            }
            
            ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream(outputFile));
            output.writeObject(rows); 
        }
        catch(IOException exception)
        {
            System.out.println(exception);
        }
    }//GEN-LAST:event_serializedSaveButtonMouseClicked

    private void serializedLoadButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serializedLoadButtonMouseClicked
        try
        {
            FileInputStream inputStream = null;
            JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            fileChooser.setAcceptAllFileFilterUsed(false);
            FileNameExtensionFilter filter = new FileNameExtensionFilter("SERIALIZED FILES", "ser");
            fileChooser.addChoosableFileFilter(filter);
            fileChooser.setCurrentDirectory(new File("F://джава/corn"));
            int returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION)
            {
                File selectedFile = fileChooser.getSelectedFile();
                inputStream = new FileInputStream(selectedFile.getAbsolutePath());
            }
            
            ObjectInputStream input = new ObjectInputStream(inputStream);
            
            rows.clear();
            ClearModel();
            
            rows = (LinkedList<RecIntegral>) input.readObject();
            FillModel();
        }
        catch(IOException | ClassNotFoundException | NullPointerException exception)
        {
            System.out.println(exception);
        }
    }//GEN-LAST:event_serializedLoadButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton fillButton;
    private javax.swing.JTable integralTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lowerLinePanel;
    private javax.swing.JLabel maxValueLabel;
    private javax.swing.JTextField maxValueTextField;
    private javax.swing.JPanel middleLinePanel;
    private javax.swing.JLabel minValueLabel;
    private javax.swing.JTextField minValueTextField;
    private javax.swing.JPanel nameLabelPanel;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton resultButton;
    private javax.swing.JButton serializedLoadButton;
    private javax.swing.JButton serializedSaveButton;
    private javax.swing.JLabel stepValueLabel;
    private javax.swing.JTextField stepValueTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton unserializedLoadButton;
    private javax.swing.JButton unserializedSaveButton;
    // End of variables declaration//GEN-END:variables
}
